In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\01_Raw_Data\iea_ev_data.xlsx")

In [3]:
df.head()

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
0,World,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,170000000.0,_World
1,World,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,150000000.0,_World
2,China,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,91000000.0,Other
3,China,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,82000000.0,Other
4,World,Projection-STEPS,EV stock,Cars,PHEV,2030,Vehicles,82000000.0,_World

In [4]:
df.shape

(16436, 9)

In [5]:
df.columns

Index(['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year',
       'unit', 'value', 'Aggregate group'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16436 entries, 0 to 16435
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region_country   16436 non-null  object
 1   category         16436 non-null  object
 2   parameter        16436 non-null  object
 3   mode             16436 non-null  object
 4   powertrain       16436 non-null  object
 5   year             16436 non-null  int64
 6   unit             16436 non-null  object
 7   value            16436 non-null  float64
 8   Aggregate group  16436 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.1+ MB

In [7]:
df.isnull().sum()

region_country     0
category           0
parameter          0
mode               0
powertrain         0
year               0
unit               0
value              0
Aggregate group    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(12)

In [9]:
df=df.drop_duplicates()

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year',
       'unit', 'value', 'Aggregate group'],
      dtype='object')

In [12]:
df["region_country"]=df["region_country"].str.strip()

In [13]:
df["category"]=df["category"].str.strip()

In [14]:
df["parameter"]=df["parameter"].str.strip()

In [15]:
df["mode"]=df["mode"].str.strip()

In [16]:
df["powertrain"]=df["powertrain"].str.strip()

In [17]:
df["unit"]=df["unit"].str.strip()

In [18]:
df["Aggregate group"]=df["Aggregate group"].str.strip()

In [19]:
df["region_country"].unique()

array(['World', 'China', 'Asia Pacific', 'India', 'Europe',
       'Rest of the world', 'USA', 'EU27', 'North America', 'Germany',
       'Viet Nam', 'United Kingdom', 'France', 'Norway', 'Canada',
       'Netherlands', 'Central and South America', 'Korea', 'Indonesia',
       'Sweden', 'Belgium', 'Denmark', 'Japan', 'Italy', 'Australia',
       'Turkiye', 'Spain', 'Switzerland', 'Austria', 'Israel', 'Thailand',
       'Finland', 'Portugal', 'Brazil', 'New Zealand',
       'Middle East and Caspian', 'Poland', 'Mexico', 'Malaysia',
       'Russia', 'Iceland', 'Greece', 'Uzbekistan', 'Africa', 'Ireland',
       'Chile', 'Costa Rica', 'Colombia', 'Romania', 'Luxembourg',
       'Czech Republic', 'Hungary', 'Slovenia', 'South Africa',
       'Slovakia', 'Lithuania', 'Bulgaria', 'Croatia', 'Latvia',
       'Estonia', 'Cyprus', 'Jordan', 'Seychelles'], dtype=object)

In [20]:
df["region_country"] = df["region_country"].replace({
    "Viet Nam": "Vietnam",
    "Korea": "South Korea",
    "Turkiye": "Turkey",
    "USA": "United States",
    "Czech Republic": "Czechia"
})

print(df["region_country"].unique())

['World' 'China' 'Asia Pacific' 'India' 'Europe' 'Rest of the world'
 'United States' 'EU27' 'North America' 'Germany' 'Vietnam'
 'United Kingdom' 'France' 'Norway' 'Canada' 'Netherlands'
 'Central and South America' 'South Korea' 'Indonesia' 'Sweden' 'Belgium'
 'Denmark' 'Japan' 'Italy' 'Australia' 'Turkey' 'Spain' 'Switzerland'
 'Austria' 'Israel' 'Thailand' 'Finland' 'Portugal' 'Brazil' 'New Zealand'
 'Middle East and Caspian' 'Poland' 'Mexico' 'Malaysia' 'Russia' 'Iceland'
 'Greece' 'Uzbekistan' 'Africa' 'Ireland' 'Chile' 'Costa Rica' 'Colombia'
 'Romania' 'Luxembourg' 'Czechia' 'Hungary' 'Slovenia' 'South Africa'
 'Slovakia' 'Lithuania' 'Bulgaria' 'Croatia' 'Latvia' 'Estonia' 'Cyprus'
 'Jordan' 'Seychelles']

In [21]:
df["category"].unique()

array(['Projection-STEPS', 'Historical'], dtype=object)

In [22]:
df["parameter"].unique()

array(['EV stock', 'EV sales', 'EV charging points', 'Electricity demand',
       'Oil displacement, million lge', 'Battery demand',
       'EV sales share', 'EV stock share', 'Oil displacement Mbd'],
      dtype=object)

In [23]:
df["powertrain"].unique()

array(['BEV', 'PHEV', 'Publicly available slow',
       'Publicly available fast', 'EV', 'FCEV'], dtype=object)

In [24]:
df["mode"].unique()

array(['2 and 3 wheelers', 'Cars', 'Vans', 'EV', 'Trucks', 'Buses'],
      dtype=object)

In [25]:
# Keep only EV sales and EV stock
df = df[df["parameter"].isin(["EV sales", "EV stock"])]

In [26]:
# Keep only Historical data
df = df[df["category"] == "Historical"]

In [27]:
# Keep years 2015 to 2024
df = df[df["year"].between(2015, 2024)]

In [28]:
df.shape

(6532, 9)

In [29]:
df["year"] = df["year"].astype(int)
df["value"] = pd.to_numeric(df["value"])

In [30]:
df.rename(columns={
    "region_country": "Country",
    "category": "Category",
    "parameter": "Parameter",
    "mode": "Mode",
    "powertrain": "Powertrain",
    "year": "Year",
    "unit": "Unit",
    "value": "Value",
    "Aggregate group": "Aggregate_Group"
}, inplace=True)

In [31]:
df.head()

,Country,Category,Parameter,Mode,Powertrain,Year,Unit,Value,Aggregate_Group
5,World,Historical,EV stock,2 and 3 wheelers,BEV,2024,Vehicles,79000000.0,_World
7,Asia Pacific,Historical,EV stock,2 and 3 wheelers,BEV,2024,Vehicles,77000000.0,Aggregate_sales_stock
8,World,Historical,EV stock,2 and 3 wheelers,BEV,2023,Vehicles,69000000.0,_World
10,Asia Pacific,Historical,EV stock,2 and 3 wheelers,BEV,2023,Vehicles,68000000.0,Aggregate_sales_stock
11,China,Historical,EV stock,2 and 3 wheelers,BEV,2024,Vehicles,67000000.0,Other

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6532 entries, 5 to 12408
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          6532 non-null   object
 1   Category         6532 non-null   object
 2   Parameter        6532 non-null   object
 3   Mode             6532 non-null   object
 4   Powertrain       6532 non-null   object
 5   Year             6532 non-null   int64
 6   Unit             6532 non-null   object
 7   Value            6532 non-null   float64
 8   Aggregate_Group  6532 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 510.3+ KB

In [33]:
df.isnull().sum()

Country            0
Category           0
Parameter          0
Mode               0
Powertrain         0
Year               0
Unit               0
Value              0
Aggregate_Group    0
dtype: int64

In [34]:
# List of regions to remove
regions_to_remove = [
    "Asia Pacific",
    "Europe",
    "EU27",
    "North America",
    "Central and South America",
    "Rest of the world",
    "Middle East and Caspian",
    "Africa"
]

# Keep only real countries + World
df = df[~df["Country"].isin(regions_to_remove)]

print("After removing regions:")
print("Total rows:", len(df))
print(df["Country"].unique())

After removing regions:
Total rows: 5024
['World' 'China' 'India' 'United States' 'Germany' 'Vietnam'
 'United Kingdom' 'France' 'Norway' 'Canada' 'Netherlands' 'South Korea'
 'Indonesia' 'Sweden' 'Belgium' 'Denmark' 'Japan' 'Italy' 'Australia'
 'Turkey' 'Spain' 'Switzerland' 'Austria' 'Israel' 'Thailand' 'Finland'
 'Portugal' 'Brazil' 'New Zealand' 'Poland' 'Mexico' 'Malaysia' 'Russia'
 'Iceland' 'Greece' 'Uzbekistan' 'Ireland' 'Chile' 'Costa Rica' 'Colombia'
 'Romania' 'Luxembourg' 'Czechia' 'Hungary' 'Slovenia' 'South Africa'
 'Slovakia' 'Lithuania' 'Bulgaria' 'Croatia' 'Latvia' 'Estonia' 'Cyprus'
 'Seychelles']

In [35]:
df.to_csv(
    r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\02_Cleaned_Data\cleaned_iea_ev_data.csv",
    index=False
)

print("Dataset cleaned and saved successfully!")

Dataset cleaned and saved successfully!