In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(
    r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\01_Raw_Data\Population_Dataset.xls",
    engine="xlrd"
)

In [3]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,108785.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,788844284.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,43844111.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106384410.0,108754449.0,...,428797338.0,440150152.0,451395343.0,462522286.0,473687685.0,484978794.0,496366058.0,508318102.0,520655398.0,532809933.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,39040039.0

In [4]:
df.shape

(265, 70)

In [5]:
df.columns.tolist()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    265 non-null    object
 1   Country Code    265 non-null    object
 2   Indicator Name  265 non-null    object
 3   Indicator Code  265 non-null    object
 4   1960            263 non-null    float64
 5   1961            263 non-null    float64
 6   1962            263 non-null    float64
 7   1963            263 non-null    float64
 8   1964            263 non-null    float64
 9   1965            263 non-null    float64
 10  1966            263 non-null    float64
 11  1967            263 non-null    float64
 12  1968            263 non-null    float64
 13  1969            263 non-null    float64
 14  1970            263 non-null    float64
 15  1971            263 non-null    float64
 16  1972            263 non-null    float64
 17  1973            263 non-null    float64
 18  1974            263 non-null    float64
 19  1975            263 non-null    float64
 20  1976            263 non-null    float64
 21  1977            263 non-null    float64
 22  1978            263 non-null    float64
 23  1979            263 non-null    float64
 24  1980            263 non-null    float64
 25  1981            263 non-null    float64
 26  1982            263 non-null    float64
 27  1983            263 non-null    float64
 28  1984            263 non-null    float64
 29  1985            263 non-null    float64
 30  1986            263 non-null    float64
 31  1987            263 non-null    float64
 32  1988            263 non-null    float64
 33  1989            263 non-null    float64
 34  1990            264 non-null    float64
 35  1991            264 non-null    float64
 36  1992            264 non-null    float64
 37  1993            264 non-null    float64
 38  1994            264 non-null    float64
 39  1995            264 non-null    float64
 40  1996            264 non-null    float64
 41  1997            264 non-null    float64
 42  1998            264 non-null    float64
 43  1999            264 non-null    float64
 44  2000            264 non-null    float64
 45  2001            264 non-null    float64
 46  2002            264 non-null    float64
 47  2003            264 non-null    float64
 48  2004            264 non-null    float64
 49  2005            264 non-null    float64
 50  2006            264 non-null    float64
 51  2007            264 non-null    float64
 52  2008            264 non-null    float64
 53  2009            264 non-null    float64
 54  2010            264 non-null    float64
 55  2011            264 non-null    float64
 56  2012            264 non-null    float64
 57  2013            264 non-null    float64
 58  2014            264 non-null    float64
 59  2015            264 non-null    float64
 60  2016            264 non-null    float64
 61  2017            264 non-null    float64
 62  2018            264 non-null    float64
 63  2019            264 non-null    float64
 64  2020            264 non-null    float64
 65  2021            264 non-null    float64
 66  2022            264 non-null    float64
 67  2023            264 non-null    float64
 68  2024            264 non-null    float64
 69  2025            264 non-null    float64
dtypes: float64(66), object(4)
memory usage: 145.0+ KB

In [7]:
df = df[["Country Name", "Country Code", "Indicator Name", "Indicator Code"] + [str(y) for y in range(2015, 2025)]]
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,"Population, total",SP.POP.TOTL,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,607123269.0,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,417536152.0,428797338.0,440150152.0,451395343.0,462522286.0,473687685.0,484978794.0,496366058.0,508318102.0,520655398.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0

In [8]:
pop_long = df.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Population"
)

pop_long.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,Aruba,ABW,"Population, total",SP.POP.TOTL,2015,107906.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,2015,607123269.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,2015,33831764.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,2015,417536152.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,2015,28157798.0

In [9]:
pop_long.shape

(2650, 6)

In [10]:
print(pop_long.isnull().sum())

Country Name       0
Country Code       0
Indicator Name     0
Indicator Code     0
Year               0
Population        10
dtype: int64

In [11]:
pop_long = pop_long.dropna(subset=["Population"])
print("After removing missing values:", pop_long.shape)

After removing missing values: (2640, 6)

In [12]:
pop_long = pop_long.rename(columns={
    "Country Name": "Country",
    "Country Code": "Country_Code",
    "Indicator Name": "Indicator_Name",
    "Indicator Code": "Indicator_Code"
})

In [13]:
regions_to_remove = [
    'Africa Eastern and Southern', 'Africa Western and Central', 'Arab World',
    'Caribbean small states', 'Central Europe and the Baltics', 'Channel Islands',
    'East Asia & Pacific (excluding high income)', 'Early-demographic dividend',
    'East Asia & Pacific', 'Europe & Central Asia (excluding high income)',
    'Europe & Central Asia', 'Euro area', 'European Union',
    'Heavily indebted poor countries (HIPC)', 'High income',
    'IBRD only', 'IDA & IBRD total', 'IDA total', 'IDA blend', 'IDA only',
    'Latin America & Caribbean (excluding high income)', 'Latin America & Caribbean',
    'Least developed countries: UN classification', 'Low income',
    'Lower middle income', 'Low & middle income', 'Late-demographic dividend',
    'Middle East, North Africa, Afghanistan & Pakistan',
    'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
    'Middle income', 'North America', 'OECD members', 'Other small states',
    'Pre-demographic dividend', 'Pacific island small states',
    'Post-demographic dividend', 'South Asia',
    'Sub-Saharan Africa (excluding high income)', 'Sub-Saharan Africa',
    'Small states', 'East Asia & Pacific (IDA & IBRD countries)',
    'Europe & Central Asia (IDA & IBRD countries)',
    'Latin America & the Caribbean (IDA & IBRD countries)',
    'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
    'South Asia (IDA & IBRD)', 'Sub-Saharan Africa (IDA & IBRD countries)',
    'Upper middle income', 'World'
]

pop_long = pop_long[~pop_long["Country"].isin(regions_to_remove)]

print("After removing regions:", pop_long.shape)

After removing regions: (2160, 6)

In [14]:
pop_long.to_csv(
    r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\02_Cleaned_Data\cleaned_population.csv",
    index=False
)

print("Population dataset cleaned successfully!")
print("Final rows:", len(pop_long))

Population dataset cleaned successfully!
Final rows: 2160