In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(
    r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\01_Raw_Data\electricity_access.xls",
    engine="xlrd"
)

In [3]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,100.000000,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.667516,NaN,NaN
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.700000,97.700000,93.400000,97.700000,97.700000,97.700000,85.300000,85.300000,NaN,NaN
3,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,51.051636,48.902228,51.338199,51.289374,51.851866,54.366012,55.683570,57.064737,NaN,NaN
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,41.800000,42.900000,45.300000,45.600000,47.000000,48.200000,48.500000,51.100000,NaN,NaN

In [4]:
df.shape

(265, 70)

In [5]:
df.columns.tolist()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025']

In [6]:
df = df[["Country Name", "Country Code", "Indicator Name", "Indicator Code"] + [str(y) for y in range(2015, 2025)]]
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,100.000000,NaN
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,33.922276,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.667516,NaN
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,71.500000,97.700000,97.700000,93.400000,97.700000,97.700000,97.700000,85.300000,85.300000,NaN
3,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,46.865483,51.051636,48.902228,51.338199,51.289374,51.851866,54.366012,55.683570,57.064737,NaN
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,42.000000,41.800000,42.900000,45.300000,45.600000,47.000000,48.200000,48.500000,51.100000,NaN

In [7]:
elec_long = df.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Access_to_Electricity"
)

elec_long.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Access_to_Electricity
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,2015,100.000000
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2015,33.922276
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,2015,71.500000
3,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,2015,46.865483
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,2015,42.000000

In [8]:
elec_long.shape

(2650, 6)

In [9]:
elec_long.isnull().sum()

Country Name               0
Country Code               0
Indicator Name             0
Indicator Code             0
Year                       0
Access_to_Electricity    292
dtype: int64

In [11]:
elec_long = elec_long.dropna(subset=["Access_to_Electricity"])
print("After removing missing values:", elec_long.shape)

After removing missing values: (2358, 6)

In [12]:
elec_long = elec_long.rename(columns={
    "Country Name": "Country",
    "Country Code": "Country_Code",
    "Indicator Name": "Indicator_Name",
    "Indicator Code": "Indicator_Code"
})

In [13]:
regions_to_remove = [
    'Africa Eastern and Southern', 'Africa Western and Central', 'Arab World',
    'Caribbean small states', 'Central Europe and the Baltics', 'Channel Islands',
    'East Asia & Pacific (excluding high income)', 'Early-demographic dividend',
    'East Asia & Pacific', 'Europe & Central Asia (excluding high income)',
    'Europe & Central Asia', 'Euro area', 'European Union',
    'Heavily indebted poor countries (HIPC)', 'High income',
    'IBRD only', 'IDA & IBRD total', 'IDA total', 'IDA blend', 'IDA only',
    'Latin America & Caribbean (excluding high income)', 'Latin America & Caribbean',
    'Least developed countries: UN classification', 'Low income',
    'Lower middle income', 'Low & middle income', 'Late-demographic dividend',
    'Middle East, North Africa, Afghanistan & Pakistan',
    'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
    'Middle income', 'North America', 'OECD members', 'Other small states',
    'Pre-demographic dividend', 'Pacific island small states',
    'Post-demographic dividend', 'South Asia',
    'Sub-Saharan Africa (excluding high income)', 'Sub-Saharan Africa',
    'Small states', 'East Asia & Pacific (IDA & IBRD countries)',
    'Europe & Central Asia (IDA & IBRD countries)',
    'Latin America & the Caribbean (IDA & IBRD countries)',
    'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
    'South Asia (IDA & IBRD)', 'Sub-Saharan Africa (IDA & IBRD countries)',
    'Upper middle income', 'World'
]

elec_long = elec_long[~elec_long["Country"].isin(regions_to_remove)]

print("After removing regions:", elec_long.shape)

After removing regions: (1926, 6)

In [14]:
elec_long.to_csv(
    r"C:\Users\Bala murukan\Downloads\New folder\EV_Intelligencee_platform\02_Cleaned_Data\cleaned_electricity_access.csv",
    index=False
)

print("Electricity Access dataset cleaned successfully!")
print("Final rows:", len(elec_long))

Electricity Access dataset cleaned successfully!
Final rows: 1926